apiVersion: v1
kind: Pod
metadata:
    labels:
      app: Dudu
      Name: Bubu

    name: bubuka-pod
    namespace: default
spec:
  containers:
    - name: dudu-container
      image: nginx:latest
      port:
        - containerPort: 80
          protocol: TCP
