apiVersion: v1
kind: Pod
metadata:
    labels:
      app: Dudu

    name: pod1
    namespace: default
spec:
  containers:
    - name: dudu-container
      image: nginx:latest
      port:
        - containerPort: 80
          protocol: TCP

---
apiVersion: v1
kind: Pod
metadata:
  name: pod2
  labels:
    app: Dudu
    namespace: default
spec:
  containers:
  - name: myapp
    image: sonambewafaa/fbclone:v2
    ports:
      - containerPort: 70

